// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dtvm/dtvm.proto

package dtvm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DTVMTeeService_Execute_FullMethodName = "/dtvm.DTVMTeeService/Execute"
)

// DTVMTeeServiceClient is the client API for DTVMTeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DTVMTeeServiceClient interface {
	Execute(ctx context.Context, in *DTVMExecutionRequest, opts ...grpc.CallOption) (*DTVMExecutionResponse, error)
}

type dTVMTeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDTVMTeeServiceClient(cc grpc.ClientConnInterface) DTVMTeeServiceClient {
	return &dTVMTeeServiceClient{cc}
}

func (c *dTVMTeeServiceClient) Execute(ctx context.Context, in *DTVMExecutionRequest, opts ...grpc.CallOption) (*DTVMExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DTVMExecutionResponse)
	err := c.cc.Invoke(ctx, DTVMTeeService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DTVMTeeServiceServer is the server API for DTVMTeeService service.
// All implementations must embed UnimplementedDTVMTeeServiceServer
// for forward compatibility.
type DTVMTeeServiceServer interface {
	Execute(context.Context, *DTVMExecutionRequest) (*DTVMExecutionResponse, error)
	mustEmbedUnimplementedDTVMTeeServiceServer()
}

// UnimplementedDTVMTeeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDTVMTeeServiceServer struct{}

func (UnimplementedDTVMTeeServiceServer) Execute(context.Context, *DTVMExecutionRequest) (*DTVMExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedDTVMTeeServiceServer) mustEmbedUnimplementedDTVMTeeServiceServer() {}
func (UnimplementedDTVMTeeServiceServer) testEmbeddedByValue()                        {}

// UnsafeDTVMTeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DTVMTeeServiceServer will
// result in compilation errors.
type UnsafeDTVMTeeServiceServer interface {
	mustEmbedUnimplementedDTVMTeeServiceServer()
}

func RegisterDTVMTeeServiceServer(s grpc.ServiceRegistrar, srv DTVMTeeServiceServer) {
	// If the following call pancis, it indicates UnimplementedDTVMTeeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DTVMTeeService_ServiceDesc, srv)
}

func _DTVMTeeService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DTVMExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DTVMTeeServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DTVMTeeService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DTVMTeeServiceServer).Execute(ctx, req.(*DTVMExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DTVMTeeService_ServiceDesc is the grpc.ServiceDesc for DTVMTeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DTVMTeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dtvm.DTVMTeeService",
	HandlerType: (*DTVMTeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _DTVMTeeService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dtvm/dtvm.proto",
}
