// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: wasm/wasm_server.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WASMVMTeeService_Execute_FullMethodName = "/wasm.WASMVMTeeService/Execute"
)

// WASMVMTeeServiceClient is the client API for WASMVMTeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WASMVMTeeServiceClient interface {
	Execute(ctx context.Context, in *WASMVMExecutionRequest, opts ...grpc.CallOption) (*WASMVMExecutionResponse, error)
}

type wASMVMTeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWASMVMTeeServiceClient(cc grpc.ClientConnInterface) WASMVMTeeServiceClient {
	return &wASMVMTeeServiceClient{cc}
}

func (c *wASMVMTeeServiceClient) Execute(ctx context.Context, in *WASMVMExecutionRequest, opts ...grpc.CallOption) (*WASMVMExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WASMVMExecutionResponse)
	err := c.cc.Invoke(ctx, WASMVMTeeService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WASMVMTeeServiceServer is the server API for WASMVMTeeService service.
// All implementations must embed UnimplementedWASMVMTeeServiceServer
// for forward compatibility.
type WASMVMTeeServiceServer interface {
	Execute(context.Context, *WASMVMExecutionRequest) (*WASMVMExecutionResponse, error)
	mustEmbedUnimplementedWASMVMTeeServiceServer()
}

// UnimplementedWASMVMTeeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWASMVMTeeServiceServer struct{}

func (UnimplementedWASMVMTeeServiceServer) Execute(context.Context, *WASMVMExecutionRequest) (*WASMVMExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedWASMVMTeeServiceServer) mustEmbedUnimplementedWASMVMTeeServiceServer() {}
func (UnimplementedWASMVMTeeServiceServer) testEmbeddedByValue()                          {}

// UnsafeWASMVMTeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WASMVMTeeServiceServer will
// result in compilation errors.
type UnsafeWASMVMTeeServiceServer interface {
	mustEmbedUnimplementedWASMVMTeeServiceServer()
}

func RegisterWASMVMTeeServiceServer(s grpc.ServiceRegistrar, srv WASMVMTeeServiceServer) {
	// If the following call pancis, it indicates UnimplementedWASMVMTeeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WASMVMTeeService_ServiceDesc, srv)
}

func _WASMVMTeeService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WASMVMExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WASMVMTeeServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WASMVMTeeService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WASMVMTeeServiceServer).Execute(ctx, req.(*WASMVMExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WASMVMTeeService_ServiceDesc is the grpc.ServiceDesc for WASMVMTeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WASMVMTeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wasm.WASMVMTeeService",
	HandlerType: (*WASMVMTeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _WASMVMTeeService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wasm/wasm_server.proto",
}
