// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wasm/wasm_server.proto

package wasm

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WASMVMExecution represents a WASMVM execution request containing
// the bytecode and input parameters to be executed in TEE environment
type WASMVMExecution struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                                    // Protocol version
	RequestId          string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                               // Unique request identifier
	Bytecode           string                 `protobuf:"bytes,3,opt,name=bytecode,proto3" json:"bytecode,omitempty"`                                                  // WASMVM bytecode (base64 encoded)
	FnName             string                 `protobuf:"bytes,4,opt,name=fn_name,json=fnName,proto3" json:"fn_name,omitempty"`                                        // Function name to execute
	Inputs             []*WasmValue           `protobuf:"bytes,5,rep,name=inputs,proto3" json:"inputs,omitempty"`                                                      // Input parameters
	Timestamp          int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                               // Timestamp of the execution request
	IsForceInterpreter bool                   `protobuf:"varint,7,opt,name=is_force_interpreter,json=isForceInterpreter,proto3" json:"is_force_interpreter,omitempty"` // Whether to force interpreter mode
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WASMVMExecution) Reset() {
	*x = WASMVMExecution{}
	mi := &file_wasm_wasm_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WASMVMExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WASMVMExecution) ProtoMessage() {}

func (x *WASMVMExecution) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_wasm_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WASMVMExecution.ProtoReflect.Descriptor instead.
func (*WASMVMExecution) Descriptor() ([]byte, []int) {
	return file_wasm_wasm_server_proto_rawDescGZIP(), []int{0}
}

func (x *WASMVMExecution) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WASMVMExecution) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WASMVMExecution) GetBytecode() string {
	if x != nil {
		return x.Bytecode
	}
	return ""
}

func (x *WASMVMExecution) GetFnName() string {
	if x != nil {
		return x.FnName
	}
	return ""
}

func (x *WASMVMExecution) GetInputs() []*WasmValue {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *WASMVMExecution) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WASMVMExecution) GetIsForceInterpreter() bool {
	if x != nil {
		return x.IsForceInterpreter
	}
	return false
}

// WASMVMExecutionResult contains the complete execution result
// including inputs, outputs, hashes, and TEE attestation data
type WASMVMExecutionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inputs        []*WasmValue           `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`                                 // Original input parameters (base64 encoded)
	OutputValues  []*WasmValue           `protobuf:"bytes,3,rep,name=output_values,json=outputValues,proto3" json:"output_values,omitempty"` // Execution output values
	Attestation   string                 `protobuf:"bytes,5,opt,name=attestation,proto3" json:"attestation,omitempty"`                       // TEE attestation report (JSON string)
	ReportData    string                 `protobuf:"bytes,6,opt,name=report_data,json=reportData,proto3" json:"report_data,omitempty"`       // TEE report data (hex encoded), hash(inputs+outputs)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WASMVMExecutionResult) Reset() {
	*x = WASMVMExecutionResult{}
	mi := &file_wasm_wasm_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WASMVMExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WASMVMExecutionResult) ProtoMessage() {}

func (x *WASMVMExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_wasm_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WASMVMExecutionResult.ProtoReflect.Descriptor instead.
func (*WASMVMExecutionResult) Descriptor() ([]byte, []int) {
	return file_wasm_wasm_server_proto_rawDescGZIP(), []int{1}
}

func (x *WASMVMExecutionResult) GetInputs() []*WasmValue {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *WASMVMExecutionResult) GetOutputValues() []*WasmValue {
	if x != nil {
		return x.OutputValues
	}
	return nil
}

func (x *WASMVMExecutionResult) GetAttestation() string {
	if x != nil {
		return x.Attestation
	}
	return ""
}

func (x *WASMVMExecutionResult) GetReportData() string {
	if x != nil {
		return x.ReportData
	}
	return ""
}

// WASMVMExecutionRequest combines execution parameters and runtime
// configuration
type WASMVMExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *WASMVMExecution       `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"` // Execution parameters (bytecode, inputs)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WASMVMExecutionRequest) Reset() {
	*x = WASMVMExecutionRequest{}
	mi := &file_wasm_wasm_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WASMVMExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WASMVMExecutionRequest) ProtoMessage() {}

func (x *WASMVMExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_wasm_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WASMVMExecutionRequest.ProtoReflect.Descriptor instead.
func (*WASMVMExecutionRequest) Descriptor() ([]byte, []int) {
	return file_wasm_wasm_server_proto_rawDescGZIP(), []int{2}
}

func (x *WASMVMExecutionRequest) GetExecution() *WASMVMExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

// WASMVMExecutionResponse contains the execution result with request tracking
type WASMVMExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Request identifier for tracking
	Result        *WASMVMExecutionResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                        // Complete execution result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WASMVMExecutionResponse) Reset() {
	*x = WASMVMExecutionResponse{}
	mi := &file_wasm_wasm_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WASMVMExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WASMVMExecutionResponse) ProtoMessage() {}

func (x *WASMVMExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wasm_wasm_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WASMVMExecutionResponse.ProtoReflect.Descriptor instead.
func (*WASMVMExecutionResponse) Descriptor() ([]byte, []int) {
	return file_wasm_wasm_server_proto_rawDescGZIP(), []int{3}
}

func (x *WASMVMExecutionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WASMVMExecutionResponse) GetResult() *WASMVMExecutionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_wasm_wasm_server_proto protoreflect.FileDescriptor

const file_wasm_wasm_server_proto_rawDesc = "" +
	"\n" +
	"\x16wasm/wasm_server.proto\x12\x04wasm\x1a\x1cgoogle/api/annotations.proto\x1a\x15wasm/wasm_input.proto\"\xf8\x01\n" +
	"\x0fWASMVMExecution\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1a\n" +
	"\bbytecode\x18\x03 \x01(\tR\bbytecode\x12\x17\n" +
	"\afn_name\x18\x04 \x01(\tR\x06fnName\x12'\n" +
	"\x06inputs\x18\x05 \x03(\v2\x0f.wasm.WasmValueR\x06inputs\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x120\n" +
	"\x14is_force_interpreter\x18\a \x01(\bR\x12isForceInterpreter\"\xb9\x01\n" +
	"\x15WASMVMExecutionResult\x12'\n" +
	"\x06inputs\x18\x01 \x03(\v2\x0f.wasm.WasmValueR\x06inputs\x124\n" +
	"\routput_values\x18\x03 \x03(\v2\x0f.wasm.WasmValueR\foutputValues\x12 \n" +
	"\vattestation\x18\x05 \x01(\tR\vattestation\x12\x1f\n" +
	"\vreport_data\x18\x06 \x01(\tR\n" +
	"reportData\"M\n" +
	"\x16WASMVMExecutionRequest\x123\n" +
	"\texecution\x18\x01 \x01(\v2\x15.wasm.WASMVMExecutionR\texecution\"m\n" +
	"\x17WASMVMExecutionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x123\n" +
	"\x06result\x18\x02 \x01(\v2\x1b.wasm.WASMVMExecutionResultR\x06result2w\n" +
	"\x10WASMVMTeeService\x12c\n" +
	"\aExecute\x12\x1c.wasm.WASMVMExecutionRequest\x1a\x1d.wasm.WASMVMExecutionResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/dtvm/executeB)Z'github.com/IntelliXLabs/wasmvm-tee/wasmb\x06proto3"

var (
	file_wasm_wasm_server_proto_rawDescOnce sync.Once
	file_wasm_wasm_server_proto_rawDescData []byte
)

func file_wasm_wasm_server_proto_rawDescGZIP() []byte {
	file_wasm_wasm_server_proto_rawDescOnce.Do(func() {
		file_wasm_wasm_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wasm_wasm_server_proto_rawDesc), len(file_wasm_wasm_server_proto_rawDesc)))
	})
	return file_wasm_wasm_server_proto_rawDescData
}

var file_wasm_wasm_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wasm_wasm_server_proto_goTypes = []any{
	(*WASMVMExecution)(nil),         // 0: wasm.WASMVMExecution
	(*WASMVMExecutionResult)(nil),   // 1: wasm.WASMVMExecutionResult
	(*WASMVMExecutionRequest)(nil),  // 2: wasm.WASMVMExecutionRequest
	(*WASMVMExecutionResponse)(nil), // 3: wasm.WASMVMExecutionResponse
	(*WasmValue)(nil),               // 4: wasm.WasmValue
}
var file_wasm_wasm_server_proto_depIdxs = []int32{
	4, // 0: wasm.WASMVMExecution.inputs:type_name -> wasm.WasmValue
	4, // 1: wasm.WASMVMExecutionResult.inputs:type_name -> wasm.WasmValue
	4, // 2: wasm.WASMVMExecutionResult.output_values:type_name -> wasm.WasmValue
	0, // 3: wasm.WASMVMExecutionRequest.execution:type_name -> wasm.WASMVMExecution
	1, // 4: wasm.WASMVMExecutionResponse.result:type_name -> wasm.WASMVMExecutionResult
	2, // 5: wasm.WASMVMTeeService.Execute:input_type -> wasm.WASMVMExecutionRequest
	3, // 6: wasm.WASMVMTeeService.Execute:output_type -> wasm.WASMVMExecutionResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_wasm_wasm_server_proto_init() }
func file_wasm_wasm_server_proto_init() {
	if File_wasm_wasm_server_proto != nil {
		return
	}
	file_wasm_wasm_input_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wasm_wasm_server_proto_rawDesc), len(file_wasm_wasm_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wasm_wasm_server_proto_goTypes,
		DependencyIndexes: file_wasm_wasm_server_proto_depIdxs,
		MessageInfos:      file_wasm_wasm_server_proto_msgTypes,
	}.Build()
	File_wasm_wasm_server_proto = out.File
	file_wasm_wasm_server_proto_goTypes = nil
	file_wasm_wasm_server_proto_depIdxs = nil
}
