name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'
          cache: true

      - name: Install cross-compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            build-essential \
            libc6-dev-arm64-cross

      - name: Set up cross-compilation environment
        run: |
          echo "CC_aarch64_linux=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "CXX_aarch64_linux=aarch64-linux-gnu-g++" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CC_linux_arm64: aarch64-linux-gnu-gcc
          CXX_linux_arm64: aarch64-linux-gnu-g++ 