name: Unit Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Add WASM target
      run: rustup target add wasm32-wasi

    - name: Install WasmEdge
      run: |
        wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.14.0
        echo "$HOME/.wasmedge/bin" >> $GITHUB_PATH

    - name: Run tests
      run: |
        source ~/.bashrc
        export LD_LIBRARY_PATH=$HOME/.wasmedge/lib:$LD_LIBRARY_PATH
        make test 